### ISSUE TITLE
Error while generating report.

### ISSUE THREAD

**Issue by thoufer** [USFWS/migbirdHIP#5]
Quitting from lines 282-313 (dl_report.Rmd) 
Error in `group_by()`:
! Must group by variables found in `.data`.
x Column `issue_id` is not found.
Backtrace:
 1. ... %>% arrange(desc(n))
 6. dplyr:::group_by.data.frame(., dl_state, registration_yr, issue_id)

I hacked the report to run it manually, removing the issue_id from the grouping and it runs, but I can't figure out what issue_id represents, and if grouping by it is necessary.

**Comment by thoufer** [comment]
hmm.  I can get the report to compile, with the issue_id present when knitting the RMD directly..

**Comment by lawalter** [comment]
@thoufer This is a really interesting error that I haven't been able to reproduce so far. I believe since `future_data` is read in by the report template, there was probably an issue with the `future_path` param provided to `writeReport()` when you did the run through. I'll send you a code snippet to troubleshoot.
